### PR TITLE
These changes are related to boot from volume feature.

### PR DESCRIPTION
**Pull request by afaheem88**
During create server function will always add block device mapping
parameter and during delete server function will try to delete the
volume created for this server.

### CODE REVIEW

**Comment by rickysarraf** [comment]
Is this also targeted for upstream, or just our own use ?

**Comment by afaheem88** [comment]
In our environment servers can be booted only through bootable volume but in upstream there is no such restriction. Soumit raised a bug also for this https://bugs.launchpad.net/tempest/+bug/1436314. So we need to add these changes in our repository in order to run temepest.

**Comment by rickysarraf** [comment]
On Wednesday 20 May 2015 02:23 PM, afaheem88 wrote:
>
> In our environment servers can be booted only through bootable volume
> but in upstream there is no such restriction. Soumit raised a bug also
> for this https://bugs.launchpad.net/tempest/+bug/1436314. So we need
> to add these changes in our repository in order to run temepest.
>
Thanks faheem.

But what is the status on that LP bug. Neither is it closed, nor
targeted to be fixes. Its current state is "invalid".

From the discussion there, it looks like the concern is about
"max_local_block_devcies" being forced to '0'. Which if done, will be
havoc for VMs that may swap. So the reasoning looks justified.

Are there plans to bring that bug to closure ?

-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by rickysarraf** [comment]
Merged into branch jiochanges

**Pull request closed without merging**
